language: php
dist: bionic

notifications:
  email:
    on_success: never
    on_failure: never

before_install:
  # turn off XDebug for speed up
  - phpenv config-rm xdebug.ini || return 0

php:
  - '7.4'

services:
  - docker

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.cache
    - $TRAVIS_BUILD_DIR/test/cypress/node_modules
    - $TRAVIS_BUILD_DIR/src/themes/starter/node_modules

addons:
  hosts:
    - gao.ddev.site

before_script:
  - sudo bash scripts/bin/install-ddev.sh
  - sudo ln -s ${TRAVIS_BUILD_DIR}/ddev /usr/local/bin/ddev
  - ddev start -j
  - ddev init

jobs:
  fast_finish: true
  include:
    -
      stage: Tests
      script:
        - ddev behat 
        # We are running cypress locally for now.
        - export CYPRESS_BASE_URL=http://`ddev exec printenv VIRTUAL_HOST`
        - export PROJECT_ROOT=`printenv TRAVIS_BUILD_DIR`
        - env
        - ${TRAVIS_BUILD_DIR}/scripts/bin/install-cypress.sh
        - ${TRAVIS_BUILD_DIR}/scripts/bin/test-cypress.sh
        # works but fails with bartik
        # - ddev pa11y
