dist: bionic

language: minimal

install:
  ## Update 'get.docksal.io' curl fails from time to time. Added '-k' to ignore cert error.
  ## ==> curl: (51) SSL: no alternative certificate subject name matches target host name 'get.docksal.io'
  - curl -kfsSL https://get.docksal.io | bash
  - fin update
  - fin version
  - fin sysinfo

before_script:
  - fin init

script:
  - fin test

after_success:
  - fin deploy

