language: php
dist: bionic

notifications:
  email:
    on_success: never
    on_failure: never

before_install:
  # turn off XDebug for speed up
  - phpenv config-rm xdebug.ini || return 0

php:
  - '7.4'

services:
  - docker

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.cache
    - $TRAVIS_BUILD_DIR/test/cypress/node_modules
    - $TRAVIS_BUILD_DIR/src/themes/starter/node_modules

before_script:
  - sudo bash scripts/bin/install-ddev.sh
  - sudo ln -s ${TRAVIS_BUILD_DIR}/ddev /usr/local/bin/ddev
  - ddev start -j
  - ddev init
  - export PROJECT_ROOT=`printenv TRAVIS_BUILD_DIR`
  - export CYPRESS_BASE_URL=http://`ddev exec printenv VIRTUAL_HOST`
  - ${TRAVIS_BUILD_DIR}/scripts/bin/install-cypress.sh

jobs:
  fast_finish: true
  include:
    -
      stage: Tests
      script:
        - ddev behat 
        # We are running cypress natively for now so no ddev command.
        - ${TRAVIS_BUILD_DIR}/scripts/bin/test-cypress.sh
        # works but fails with emulsify out of the box 
        # - ddev pa11y

      stage: D8_Core_Update
      if: branch = update
      env: TRAVIS_EVENT_TYPE=cron
        - echo "From D8_Core_Update"
