version: "2.1"

services:
  cli:
    environment:
      - IS_DOCKSAL_PROJECT
      - THEME_NAME

  solr:
    image: docksal/solr:4.x
    extends:
      file: ${HOME}/.docksal/stacks/services.yml
      service: solr

  memcached:
    extends:
      file: ${HOME}/.docksal/stacks/services.yml
      service: memcached
    command: ["-m", "256"]

  pa11y:
    hostname: pa11y
    image: drydockcloud/ca-pa11y:0.1
    command: tail -f /dev/null
    volumes:
      - ../tests/pa11y/wcag2-config.json:/home/node/app/wcag2-config.json
